drop table user if exists;
create table user (
	id bigint generated by default as identity,
	username varchar(40),
	name varchar(20),
	age int(3),
	balance decimal(10,2),
	primary key(id) --指定主键
);


insert into user (id,username,name,age,balance) values(1 ,'account1','张三',30,1000.00);

insert into user (id,username,name,age,balance) values(1 ,'account1','李四',20,100.00);

insert into user (id,username,name,age,balance) values(1 ,'account1','王五',41,10000.00);

insert into user (id,username,name,age,balance) values(1 ,'account1','刘六',30,100000.00);